services:
  - type: web
    name: lamar-app
    runtime: node
    repo: https://github.com/sohaib-creator/LamarApp
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: gateway01.eu-central-1.prod.aws.tidbcloud.com
      - key: DB_PORT
        value: 4000
      - key: DB_USER
        value: 2bK5HBexjUuaa4o.root
      - key: DB_PASSWORD
        value: x9fK9pLFTLAPCcT7
      - key: DB_NAME
        value: lamar_app_db
      - key: DB_SSL
        value: 'true'
      - key: JWT_SECRET
        value: lamar_2024_super_secret_key_change_in_production
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: FRONTEND_URL
        value: https://lamarapp.site.je
      - key: API_URL
        value: https://lamarapp.onrender.com
      - key: CORS_ORIGIN
        value: 'https://lamarapp.site.je,https://lamar-app.onrender.com,https://lamarapp.onrender.com'
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: '587'
      - key: SMTP_SECURE
        value: 'false'
      - key: SMTP_USER
        value: lamarwater1@gmail.com
      - key: SMTP_PASS
        value: newp pupr twfk jeli
      - key: EMAIL_FROM
        value: lamarwater1@gmail.com
