services:
  - type: web
    name: lamar-app
    runtime: node
    repo: https://github.com/sohaib-creator/LamarApp
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: sql303.infinityfree.com
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: if0_42206887
      - key: DB_PASSWORD
        value: Zdcee8t7QH
      - key: DB_NAME
        value: if0_42206887_lamardb
      - key: JWT_SECRET
        value: lamar_2024_super_secret_key_change_in_production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://lamarapp.site.je
      - key: API_URL
        value: https://lamar-app.onrender.com
      - key: CORS_ORIGIN
        value: 'https://lamarapp.site.je,https://lamar-app.onrender.com'
